title: <p align="center"> Shivam Sachdeva </p>
logo: /assets/img/viber_image_2022-09-06_09-09-07-262.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shivam-sachdeva-614175111</a> |
  <a href="https://github.com/sachdeva-shivam">GitHub</a>
  
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
